### ISSUE TITLE
hkmeans only takes euclidean distance

### ISSUE THREAD

**Issue by santsang** [kassambara/factoextra#52]
Hi

I would like to use other (dis-) similarity measures.  I understand that I can use get_dist() with hc.metric to specify the measure I want to use.  I ended up obtaining the results generated based on euclidean distance for all cases.

All the best

Sandro

**Comment by santsang** [comment]
No suggestion or action for fixing the bugs?  Sandro

**Comment by kassambara** [comment]
fixed now, thanks

**Comment by santsang** [comment]
Thanks.  I will let you know the outcome.  Sandro

**Comment by santsang** [comment]
Hi Kassambara

Happy New Year.

The outcome suggests that the function still does not take other distance.  The webpage of your package suggests that you have not upload the modified one.

All the best

Sandro
